FROM julia:latest


# --- required packages --- #
RUN apt-get update && \
    apt-get install -y build-essential && \
    libatomic1 && \
    python && \
    gfortran && \
    perl && \
    wget && \
    m4 && \
    cmake && \
    pkg-config && \
    git && \
